"""
chunk_and_merge.py
------------------
Processes long transcripts by splitting into chunks, running each through the LLM,
then merging all outputs into one cohesive document.
"""

import requests
from pathlib import Path

# Default settings
CHUNK_SIZE_TOKENS = 3500  # Further reduced for faster processing and more focused output
DEFAULT_MODEL = "llama3.1:8b"  # Back to 8b for better instruction-following


def count_tokens(text: str) -> int:
    """Rough token estimate: ~4 chars per token"""
    return len(text) // 4


def split_into_chunks(text: str, chunk_size: int = CHUNK_SIZE_TOKENS) -> list:
    """Split text into chunks by token count, trying to break at sentence boundaries."""
    sentences = text.split('. ')
    chunks = []
    current_chunk = ""
    
    for sentence in sentences:
        sentence = sentence.strip() + ". "
        test_chunk = current_chunk + sentence
        
        if count_tokens(test_chunk) <= chunk_size:
            current_chunk = test_chunk
        else:
            if current_chunk:
                chunks.append(current_chunk.strip())
            current_chunk = sentence
    
    if current_chunk.strip():
        chunks.append(current_chunk.strip())
    
    return chunks


def process_chunk(chunk_text: str, chunk_num: int, total_chunks: int, model: str = DEFAULT_MODEL) -> str:
    """Process a single chunk through the LLM - uses original meeting documentation prompt."""
    url = "http://localhost:11434/api/generate"
    
    # Calculate word count for minimum output requirement
    word_count = len(chunk_text.split())
    min_output_words = max(1200, word_count // 2)  # At least 1200 words or 50% of input
    
    prompt = f"""You are a professional meeting documentarian producing a **complete, structured meeting record** for internal company use. The audio transcript is a mix of English, Tagalog, and Bicolano dialect generated by a Whisper speech-to-text model.

Your job is NOT to summarize. Your job is to **reconstruct the full meeting in writing** — capturing every significant topic, decision, anecdote, demonstration, quote, name, number, and event in the order they occurred.

---

### CRITICAL OUTPUT OVERRIDE

**OUTPUT LENGTH REQUIREMENT:** This transcript chunk contains {word_count} words. You MUST produce at least {min_output_words} words of detailed meeting record. This is NOT optional.

**ANTI-SUMMARY RULE:** Do NOT produce a summary. Do NOT produce bullet points only. Do NOT produce brief overviews. Produce a detailed narrative document with full paragraphs for each topic discussed.

**FORBIDDEN PHRASES:** Never start your response with phrases like:
- "Certainly! Here's a structured summary..."
- "Here's a summary of..."
- "In summary,..."
- "To summarize,..."
- "The key points are..."
- Any similar introductory summary phrases

**NEVER ADD ANY STATUS MESSAGE:** Do NOT add any "Status:", "Note:", "Summary:" or similar self-referential messages at the end of your output. Just produce the meeting record content directly.

**NO PLACEHOLDERS:** Do NOT use placeholders like [Insert Date], [Insert Names], [Speaker], or brackets of any kind. If the transcript does not provide a specific name or date, omit that field entirely. Do not invent or label empty fields.

**NO EXTRA SECTIONS:** Do NOT add sections like Attendees, Agenda, Key Takeaways, Action Items, Next Steps, Recommendations, or Conclusion unless they appear verbatim in the transcript. The ONLY top-level sections allowed are the ones in the required format below.

Start directly with the meeting record content. No preamble. No trailing status messages.

---

### LANGUAGE INSTRUCTIONS

- The transcript will contain code-switched speech (English + Tagalog + Bicolano mixed together, sometimes within the same sentence).
- **Translate everything into clear, professional English.** Do not leave Tagalog or Bicolano words untranslated in your output.
- If a phrase is a filler, repetition, or transcription artifact (e.g., stutters, "uh", "ano", "kasi"), ignore it.
- Preserve the **meaning and tone** of what was said, including humor, frustration, emphasis, or personal anecdotes.
- If a speaker used a specific number, name, statistic, quote, or proper noun — **include it exactly as stated.**

---

### STRUCTURAL INSTRUCTIONS

Organize the output **chronologically**, following the actual sequence of events in the meeting. Use numbered sections for each distinct segment (e.g., pre-session setup, opening remarks, each presenter's segment, Q&A, closing). Within each section, use sub-headers and bullet points to capture detail.

**For each section, capture:**
- Who was speaking or presenting (use actual names or roles if discernible from context)
- What they said, showed, or decided — in as much detail as the transcript allows
- Any specific examples, analogies, stories, or demonstrations they walked through
- Any questions, reactions, or responses from the audience or other speakers
- Any decisions made, tasks assigned, or next steps mentioned

Do **not** compress, skip, or generalize. If the speaker told a long personal story, document the story. If a demonstration walked through multiple steps, document each step. If a debate had two sides, document both sides.

---

### OUTPUT FORMAT - MANDATORY HORIZONTAL RULES

You MUST use horizontal rules between major sections. The format is:

```
# [Derive a fitting session title from the content]

## Executive Summary
[Write this section LAST, after completing the full record below. 
Provide 4–8 sentences covering: the purpose of the session, the key themes, 
major decisions or announcements made, and overall outcome. 
This should read as a standalone briefing for someone who did not attend.]

---

## Full Meeting Record

### 1. [Section Title — e.g., "Pre-Session Setup"]
[Content - use full paragraphs, not just bullet points]

### 2. [Section Title — e.g., "Opening Video: Topic"]
[Content - detailed paragraphs]

### 3. [Section Title — derived from what actually happened]
[Content - detailed paragraphs]

... continue for all sections in chronological order ...
```

**BRIEF EXAMPLE (FORMAT ONLY — NOT CONTENT):**

```
# Session Title Placeholder

## Executive Summary
This session covered [topic], focusing on [theme], [decision], and [outcome].

---

## Full Meeting Record

### 1. Opening Remarks
The speaker introduced [context] and outlined the agenda.

---

### 2. Main Discussion
The presenter explained [detail] and gave the example of [example].
```

**CRITICAL FORMATTING RULES:**
- Use `##` for major structural blocks (Executive Summary, Full Meeting Record)
- Use `###` for numbered chronological sections
- Use `####` for sub-topics within a section when a speaker covered multiple distinct points
- Use `-` bullet points for lists of items, decisions, or sub-points
- Use `**bold**` to highlight decisions, names being formally announced, or key terms
- Use `> blockquote` for direct quotes or near-verbatim statements from speakers
- **MUST USE `---` (horizontal rule) between Executive Summary and Full Meeting Record**
- **MUST USE `---` (horizontal rule) between each major section**
- The output should be as long as the content demands. Do not truncate.
- **DO NOT ADD ANY OTHER TOP-LEVEL HEADERS** beyond the required format above.

---

### QUALITY CHECKS BEFORE OUTPUTTING

Before finalizing, verify:
1. Does the Executive Summary reflect the actual content below it?
2. Are all sections in the correct chronological order?
3. Have you captured every named person, specific number, product, statistic, or proper noun mentioned?
4. Have you included personal anecdotes and stories told by speakers — not just abstract points?
5. Is everything written in English (no Tagalog or Bicolano left untranslated)?
6. Does the output use proper Markdown with consistent header levels?
7. **Have you produced at least {min_output_words} words of detailed content?**
8. **Did you avoid starting with any summary preamble phrases?**
9. **Did you include `---` horizontal rules between major sections?**
10. **Did your output match the example format above (headers and separators)?**
11. **Did you NOT add any "Status:" or trailing messages?**
12. **Did you avoid placeholders and extra sections?**

---

### EDGE CASES

- **If the transcript is very short** (less than 5 meaningful sentences — e.g., just a mic test or greeting): skip the Full Meeting Record structure entirely and output only: `**Status:** Short audio test or greeting detected. No substantive meeting content to document.`
- **If a section of the transcript is inaudible or garbled** beyond interpretation: note it inline as `*[Inaudible or unclear segment — transcription artifact]*` and continue.
- **If multiple people are speaking at once** and it is unclear who said what: attribute to `[Speaker]` and document the content.

---

**CONTEXT:** This is chunk {chunk_num} of {total_chunks} from the full transcript. Focus on documenting the content from this specific chunk only. The previous and next chunks will be merged with this one.

TRANSCRIPT CHUNK {chunk_num} OF {total_chunks}:
{chunk_text}

Meeting Record:"""

    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False
    }
    
    try:
        response = requests.post(url, json=payload, timeout=600)
        response.raise_for_status()
        return response.json().get("response", "")
    except Exception as e:
        return f"Error processing chunk {chunk_num}: {str(e)}"


def merge_chunks(results: list) -> str:
    """Merge multiple chunk outputs into one final document."""
    if not results:
        return "Error: No results to merge."
    
    if len(results) == 1:
        return results[0]
    
    # For multi-chunk results, combine them seamlessly
    merged = []
    for i, result in enumerate(results):
        # Clean up the result: remove any "Status:" messages, chunk markers, etc.
        lines = result.split('\n')
        filtered_lines = []
        skip_until_next_section = False
        
        for line in lines:
            # Skip status messages and chunk markers
            if line.strip().startswith('**Status:**') or line.strip().startswith('Status:'):
                continue
            if '--- CHUNK' in line:
                continue
            if 'CHUNK' in line and 'of' in line.lower() and 'transcript' in line.lower():
                continue
            
            # Remove duplicate Executive Summary from chunks after the first
            if '## Executive Summary' in line:
                skip_until_next_section = True
            elif '## Full Meeting Record' in line or '### 1.' in line:
                skip_until_next_section = False
            
            if not skip_until_next_section:
                filtered_lines.append(line)
        
        cleaned_result = '\n'.join(filtered_lines).strip()
        if cleaned_result:
            merged.append(cleaned_result)
    
    # Join with horizontal rule for readability
    return '\n\n---\n\n'.join(merged)


def process_full_transcript(transcript: str, model: str = DEFAULT_MODEL) -> str:
    """Main function: takes full transcript, returns complete meeting record."""
    print(f"Processing transcript ({count_tokens(transcript)} tokens)...")
    
    # Split into chunks
    chunks = split_into_chunks(transcript, CHUNK_SIZE_TOKENS)
    total = len(chunks)
    
    print(f"Split into {total} chunks for processing...")
    
    # Process each chunk
    results = []
    for i, chunk in enumerate(chunks):
        print(f"Processing chunk {i+1}/{total}...")
        result = process_chunk(chunk, i+1, total, model)
        results.append(result)
    
    # Merge results
    print("Merging all chunks...")
    final = merge_chunks(results)
    
    print("Done!")
    return final


# Standalone test
if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python chunk_and_merge.py <transcript_file.txt>")
        sys.exit(1)
    
    transcript_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "meeting_record.md"
    
    transcript = Path(transcript_file).read_text(encoding='utf-8')
    result = process_full_transcript(transcript)
    
    Path(output_file).write_text(result, encoding='utf-8')
    print(f"Output saved to {output_file}")
