import requests
import json

def summarize(new_transcript: str, prior_summary: str = "", model: str = "llama3.1:8b") -> str:
    """Send transcript to local Ollama LLM for structured analysis."""
    url = "http://localhost:11434/api/generate"
    
    # Calculate word count for minimum output requirement
    word_count = len(new_transcript.split())
    min_output_words = max(1200, word_count // 2)  # At least 1200 words or 50% of input
    
    prompt = f"""You are a professional meeting documentarian producing a **complete, structured meeting record** for internal company use. The audio transcript is a mix of English, Tagalog, and Bicolano dialect generated by a Whisper speech-to-text model.

Your job is NOT to summarize. Your job is to **reconstruct the full meeting in writing** — capturing every significant topic, decision, anecdote, demonstration, quote, name, number, and event in the order they occurred.

---

### CRITICAL OUTPUT OVERRIDE

**OUTPUT LENGTH REQUIREMENT:** This transcript contains {word_count} words. You MUST produce at least {min_output_words} words of detailed meeting record. This is NOT optional.

**ANTI-SUMMARY RULE:** Do NOT produce a summary. Do NOT produce bullet points only. Do NOT produce brief overviews. Produce a detailed narrative document with full paragraphs for each topic discussed.

**FORBIDDEN PHRASES:** Never start your response with phrases like:
- "Certainly! Here's a structured summary..."
- "Here's a summary of..."
- "In summary,..."
- "To summarize,..."
- "The key points are..."
- Any similar introductory summary phrases

**NEVER ADD ANY STATUS MESSAGE:** Do NOT add any "Status:", "Note:", "Summary:" or similar self-referential messages at the end of your output. Just produce the meeting record content directly.

**NO PLACEHOLDERS:** Do NOT use placeholders like [Insert Date], [Insert Names], [Speaker], or brackets of any kind. If the transcript does not provide a specific name or date, omit that field entirely. Do not invent or label empty fields.

**NO EXTRA SECTIONS:** Do NOT add sections like Attendees, Agenda, Key Takeaways, Action Items, Next Steps, Recommendations, or Conclusion unless they appear verbatim in the transcript. The ONLY top-level sections allowed are the ones in the required format below.

Start directly with the meeting record content. No preamble. No trailing status messages.

---

### LANGUAGE INSTRUCTIONS

- The transcript will contain code-switched speech (English + Tagalog + Bicolano mixed together, sometimes within the same sentence).
- **Translate everything into clear, professional English.** Do not leave Tagalog or Bicolano words untranslated in your output.
- If a phrase is a filler, repetition, or transcription artifact (e.g., stutters, "uh", "ano", "kasi"), ignore it.
- Preserve the **meaning and tone** of what was said, including humor, frustration, emphasis, or personal anecdotes.
- If a speaker used a specific number, name, statistic, quote, or proper noun — **include it exactly as stated.**

---

### STRUCTURAL INSTRUCTIONS

Organize the output **chronologically**, following the actual sequence of events in the meeting. Use numbered sections for each distinct segment (e.g., pre-session setup, opening remarks, each presenter's segment, Q&A, closing). Within each section, use sub-headers and bullet points to capture detail.

**For each section, capture:**
- Who was speaking or presenting (use actual names or roles if discernible from context)
- What they said, showed, or decided — in as much detail as the transcript allows
- Any specific examples, analogies, stories, or demonstrations they walked through
- Any questions, reactions, or responses from the audience or other speakers
- Any decisions made, tasks assigned, or next steps mentioned

Do **not** compress, skip, or generalize. If the speaker told a long personal story, document the story. If a demonstration walked through multiple steps, document each step. If a debate had two sides, document both sides.

---

### OUTPUT FORMAT - MANDATORY HORIZONTAL RULES

You MUST use horizontal rules between major sections. The format is:

```
# [Derive a fitting session title from the content]

## Executive Summary
[Write this section LAST, after completing the full record below. 
Provide 4–8 sentences covering: the purpose of the session, the key themes, 
major decisions or announcements made, and overall outcome. 
This should read as a standalone briefing for someone who did not attend.]

---

## Full Meeting Record

### 1. [Section Title — e.g., "Pre-Session Setup"]
[Content - use full paragraphs, not just bullet points]

### 2. [Section Title — e.g., "Opening Video: Topic"]
[Content - detailed paragraphs]

### 3. [Section Title — derived from what actually happened]
[Content - detailed paragraphs]

... continue for all sections in chronological order ...
```

**BRIEF EXAMPLE (FORMAT ONLY — NOT CONTENT):**

```
# Session Title Placeholder

## Executive Summary
This session covered [topic], focusing on [theme], [decision], and [outcome].

---

## Full Meeting Record

### 1. Opening Remarks
The speaker introduced [context] and outlined the agenda.

---

### 2. Main Discussion
The presenter explained [detail] and gave the example of [example].
```

**CRITICAL FORMATTING RULES:**
- Use `##` for major structural blocks (Executive Summary, Full Meeting Record)
- Use `###` for numbered chronological sections
- Use `####` for sub-topics within a section when a speaker covered multiple distinct points
- Use `-` bullet points for lists of items, decisions, or sub-points
- Use `**bold**` to highlight decisions, names being formally announced, or key terms
- Use `> blockquote` for direct quotes or near-verbatim statements from speakers
- **MUST USE `---` (horizontal rule) between Executive Summary and Full Meeting Record**
- **MUST USE `---` (horizontal rule) between each major section**
- The output should be as long as the content demands. Do not truncate.
- **DO NOT ADD ANY OTHER TOP-LEVEL HEADERS** beyond the required format above.

---

### QUALITY CHECKS BEFORE OUTPUTTING

Before finalizing, verify:
1. Does the Executive Summary reflect the actual content below it?
2. Are all sections in the correct chronological order?
3. Have you captured every named person, specific number, product, statistic, or proper noun mentioned?
4. Have you included personal anecdotes and stories told by speakers — not just abstract points?
5. Is everything written in English (no Tagalog or Bicolano left untranslated)?
6. Does the output use proper Markdown with consistent header levels?
7. **Have you produced at least {min_output_words} words of detailed content?**
8. **Did you avoid starting with any summary preamble phrases?**
9. **Did you include `---` horizontal rules between major sections?**
10. **Did your output match the example format above (headers and separators)?**
11. **Did you NOT add any "Status:" or trailing messages?**
12. **Did you avoid placeholders and extra sections?**

---

### EDGE CASES

- **If the transcript is very short** (less than 5 meaningful sentences — e.g., just a mic test or greeting): skip the Full Meeting Record structure entirely and output only: `**Status:** Short audio test or greeting detected. No substantive meeting content to document.`
- **If a section of the transcript is inaudible or garbled** beyond interpretation: note it inline as `*[Inaudible or unclear segment — transcription artifact]*` and continue.
- **If multiple people are speaking at once** and it is unclear who said what: attribute to `[Speaker]` and document the content.

---

TRANSCRIPT TO PROCESS:
{new_transcript}

{"""Previous Meeting Record (for context continuity):""" + prior_summary + "\n" if prior_summary else ""}

Meeting Record:"""

    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False
    }

    try:
        response = requests.post(url, json=payload, timeout=600)  # 10 min timeout for 7b model
        response.raise_for_status()
        return response.json().get("response", "")
    except Exception as e:
        return f"Error during summarization: {str(e)}"
